version: "3.7"
services:
  maria:
    build:
      context: .
      dockerfile: docker/maria/dev.Dockerfile
    image: maria_di
    ports:
      - 3360:3306
    volumes:
      - ./.mariadb:/var/lib/mysql
      - ./docker/maria/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - foodunit_dn
  server:
    build:
      context: .
      dockerfile: docker/server/dev.Dockerfile
    image: server_di
    ports:
      - 9292:9292
    volumes:
      - ./:/foodunit
    environment:
      - PORT=9292
      - DSN="root:root@(maria:3306)/foodunit?parseTime=true"
    networks:
      - foodunit_dn
    depends_on:
      - maria
  ui:
    build:
      context: .
      dockerfile: docker/ui/dev.Dockerfile
    image: ui_di
    ports:
      - 8080:3000
    volumes:
      - ./ui:/app
      - ./ui/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - foodunit_dn
    depends_on:
      - server
networks:
  foodunit_dn:
    name: foodunit_dn
    driver: bridge
