version: "3.7"
services:
  db:
    image: mysql:5.7
    ports:
    - "9906:3306"
    environment:
      MYSQL_DATABASE: foodunit2
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: foodunit2
    networks:
    - funet
    volumes:
    - .docker/sql:/docker-entrypoint-initdb.d
    restart: on-failure
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    image: foodunit
    ports:
    - "8080:80"
    networks:
    - funet
    volumes:
    - .:/srv/app/public
    - /srv/app/public/api/vendor
    depends_on:
    - db
    restart: on-failure
networks:
  funet:
    driver: bridge
