version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: foodunit
    ports:
    - 8080:80
    volumes:
    - .:/srv/app/public
    links:
    - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: foodunit2
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: foodunit2
    volumes:
      - .docker/sql:/docker-entrypoint-initdb.d
