version: 2
jobs:
  server-build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/dominikbraun/foodunit
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
            - go-mod-v1-
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ checksum "go.mod" }}
          paths:
            - /go/pkg
workflows:
  version: 2
  all-builds:
    jobs:
      - server-build