version: 2
jobs:
  server-build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/dominikbraun/foodunit
    environment:
      GO111MODULE: on
    steps:
      - checkout
workflows:
  version: 2
  all-builds:
    jobs:
      - server-build