version: 2
jobs:
  build_one:
    docker:
        - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build 1"
      - run: sleep 25
  build_two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Build 2"
      - run: sleep 15
workflows:
  version: 2
  build_one_and_two:
      jobs:
        - build_one
        - build_two